
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

public class ManageProducts extends javax.swing.JFrame {
    /**
     * Creates new form Seller
     */
    public ManageProducts() {
        initComponents();
        setResizable(false);
        Table();
        updateCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        back_button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        product_id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        category = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        add_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        clear_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        delete_button1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(5, 5, 65));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/small-HAPPY_MINI_MART__1_-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 359, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 520));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(4, 40, 86));
        jPanel3.setPreferredSize(new java.awt.Dimension(89, 44));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manage Products");

        back_button.setBackground(new java.awt.Color(4, 4, 76));
        back_button.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        back_button.setForeground(new java.awt.Color(255, 255, 255));
        back_button.setText("Back");
        back_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back_button)
                .addGap(40, 40, 40))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(back_button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(5, 5, 65));
        jLabel5.setText("Product ID");

        product_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        product_id.setForeground(new java.awt.Color(5, 5, 65));
        product_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_idActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(5, 5, 65));
        jLabel6.setText("Name");

        name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name.setForeground(new java.awt.Color(5, 5, 65));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(5, 5, 65));
        jLabel7.setText("Category");

        category.setForeground(new java.awt.Color(5, 5, 65));
        category.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                categoryItemStateChanged(evt);
            }
        });
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(5, 5, 65));
        jLabel8.setText("Quantity");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(5, 5, 65));
        jLabel9.setText("Price");

        quantity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        quantity.setForeground(new java.awt.Color(5, 5, 65));

        price.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        price.setForeground(new java.awt.Color(5, 5, 65));
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });

        productTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        productTable.setForeground(new java.awt.Color(5, 5, 65));
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Category", "Quantity", "Price"
            }
        ));
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productTable);

        add_button.setBackground(new java.awt.Color(4, 4, 76));
        add_button.setForeground(new java.awt.Color(255, 255, 255));
        add_button.setText("ADD");
        add_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        update_button.setBackground(new java.awt.Color(4, 4, 76));
        update_button.setForeground(new java.awt.Color(255, 255, 255));
        update_button.setText("UPDATE");
        update_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        clear_button.setBackground(new java.awt.Color(4, 4, 76));
        clear_button.setForeground(new java.awt.Color(255, 255, 255));
        clear_button.setText("CLEAR");
        clear_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_buttonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(5, 5, 65));
        jLabel3.setText("Product Details:");

        delete_button1.setBackground(new java.awt.Color(4, 4, 76));
        delete_button1.setForeground(new java.awt.Color(255, 255, 255));
        delete_button1.setText("DELETE");
        delete_button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(product_id)
                                    .addComponent(name)
                                    .addComponent(category, 0, 151, Short.MAX_VALUE))
                                .addGap(143, 143, 143))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(add_button)
                                .addGap(56, 56, 56)
                                .addComponent(update_button)
                                .addGap(56, 56, 56)
                                .addComponent(delete_button1)
                                .addGap(56, 56, 56)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(quantity, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(price)))
                            .addComponent(clear_button))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(product_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_button)
                    .addComponent(update_button)
                    .addComponent(clear_button)
                    .addComponent(delete_button1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 800, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void product_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_idActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
         new SellerFront().setVisible(true);
    }//GEN-LAST:event_back_buttonActionPerformed

    public void Table(){
        try{
           Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/happyminimart","root","");
           Statement st=c.createStatement();
           ResultSet rs=st.executeQuery("SELECT * FROM PRODUCT");
           productTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
          System.out.println(e);  
        }
    }
    
    private void clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_buttonActionPerformed
        product_id.setText("");
        name.setText("");
        quantity.setText("");
        price.setText("");
        category.setSelectedIndex(0);
    }//GEN-LAST:event_clear_buttonActionPerformed

    public void updateCombobox(){
        String query="SELECT * FROM CATEGORY";
        try{
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/happyminimart","root","");
            PreparedStatement ps=c.prepareStatement(query);
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
             category.addItem(rs.getString("NAME"));   
            }
        }catch(Exception e){
        
    }
    }
            
    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        String cate=category.getSelectedItem().toString();
        cat=cate;
    }//GEN-LAST:event_categoryActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        String pid=product_id.getText().trim();
        String pname=name.getText().trim();
        String pquan=quantity.getText().trim();
        String ppric=price.getText().trim();
        if(pid.equals("") || pname.equals("") || pquan.equals("") || ppric.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Invalid information.\nPlease select product to edit product information!","Message",JOptionPane.WARNING_MESSAGE);
        }
        else{
        try{
                Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/happyminimart","root","");
                String pi=pid;
                String pn=pname;
                String pc=category.getSelectedItem().toString();
                String pq=pquan;
                String pp=ppric;
                
                String query="UPDATE PRODUCT SET NAME=?,CATEGORY=?,QUANTITY=?,PRICE=? WHERE ID=?";
                PreparedStatement ps=c.prepareStatement(query);
                ps.setString(1,pn);
                ps.setString(2,pc);
                ps.setString(3,pq);
                ps.setString(4,pp);
                ps.setString(5,pi);
                
                ps.executeUpdate();
                
                Table();
                JOptionPane.showMessageDialog(null,"Product updated Successfully!","Message",JOptionPane.INFORMATION_MESSAGE);
            }catch(Exception e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_update_buttonActionPerformed

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        String pid=product_id.getText().trim();
        String pname=name.getText().trim();
        String pquan=quantity.getText().trim();
        String ppric=price.getText().trim();
        String pcat=category.getSelectedItem().toString();
        if(pid.equals("") || pname.equals("") || pquan.equals("") || ppric.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Invalid information.\nPlease fill all the fields to add product!","Message",JOptionPane.WARNING_MESSAGE);
        }
        else{
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/happyminimart","root","");
                String quer="INSERT INTO PRODUCT VALUES (?,?,?,?,?)";
                PreparedStatement ps=c.prepareStatement(quer);
                ps.setString(1,pid);
                ps.setString(2,pname);
                ps.setString(3,pcat);
                ps.setString(4,pquan);
                ps.setString(5,ppric);
                
                int t=ps.executeUpdate();
                
                if(t>0){
                    Table();
                  JOptionPane.showMessageDialog(null,"Product added Successfully!","Message",JOptionPane.INFORMATION_MESSAGE); 
                }
                
            }catch(SQLIntegrityConstraintViolationException e){
                JOptionPane.showMessageDialog(null,"Product ID already exists!","Message",JOptionPane.WARNING_MESSAGE);
        }catch(Exception e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_add_buttonActionPerformed

    private void delete_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_button1ActionPerformed
        String pid=product_id.getText().trim();
        String pname=name.getText().trim();
        String pquan=quantity.getText().trim();
        String ppric=price.getText().trim();
        
        if(pid.equals("") && pname.equals("") && pquan.equals("") && ppric.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Invalid information.\nPlease provide valid Product ID to delete!","Message",JOptionPane.WARNING_MESSAGE);
        }
        else{
        try{
                Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/happyminimart","root","");
                String id=product_id.getText();
                String query="DELETE FROM PRODUCT WHERE ID=?";
                PreparedStatement ps=c.prepareStatement(query);
                ps.setString(1,id);
                
                int t=ps.executeUpdate();
                Table();
                JOptionPane.showMessageDialog(null,"Product deleted Successfully!","Message",JOptionPane.INFORMATION_MESSAGE);
            }catch(Exception e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_delete_button1ActionPerformed

    private void categoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_categoryItemStateChanged

    }//GEN-LAST:event_categoryItemStateChanged

    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseClicked
        DefaultTableModel model=(DefaultTableModel)productTable.getModel();
        int obj=productTable.getSelectedRow();
        product_id.setText(model.getValueAt(obj,0).toString());
        name.setText(model.getValueAt(obj,1).toString());
        category.setSelectedItem(model.getValueAt(obj,2).toString());
        quantity.setText(model.getValueAt(obj,3).toString());
        price.setText(model.getValueAt(obj,4).toString());
    }//GEN-LAST:event_productTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JButton back_button;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JButton clear_button;
    private javax.swing.JButton delete_button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    private javax.swing.JTable productTable;
    private javax.swing.JTextField product_id;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
    String cat;
}
